project:
  type: book

book:
  title: "Titanic for the Braves"
  author: "Rodrigo Toledo"

  chapters:
    - index.qmd
    - chapters/01-introducao.qmd
    - lessons/01-conhecendo-o-titanic.ipynb

format:
  html:
    theme: cosmo
    css: custom.css
    toc: false
    grid:
      body-width: 1400px
